# Generated by Django 5.0.4 on 2026-02-27 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('key', models.CharField(max_length=128)),
                ('value', models.FloatField()),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_metrics', to='bots.bot')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['bot', 'key', '-recorded_at'], name='metrics_cus_bot_id_7b9e8f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ErrorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('error_type', models.CharField(max_length=256)),
                ('message', models.TextField()),
                ('traceback', models.TextField(blank=True)),
                ('command', models.CharField(blank=True, max_length=256)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_events', to='bots.bot')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['bot', '-recorded_at'], name='metrics_err_bot_id_23170b_idx')],
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('command', models.CharField(max_length=256)),
                ('user_id_hash', models.CharField(max_length=64)),
                ('response_time_ms', models.PositiveIntegerField()),
                ('success', models.BooleanField()),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_logs', to='bots.bot')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['bot', '-recorded_at'], name='metrics_req_bot_id_f6d167_idx'), models.Index(fields=['bot', 'command'], name='metrics_req_bot_id_7f3680_idx')],
            },
        ),
    ]
