# Generated by Django 5.0.4 on 2026-02-27 16:48

import apps.bots.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
                ('api_key', models.CharField(default=apps.bots.models.generate_api_key, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Heartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('uptime_seconds', models.PositiveIntegerField()),
                ('cpu_percent', models.FloatField()),
                ('memory_mb', models.FloatField()),
                ('active_connections', models.PositiveIntegerField()),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='bots.bot')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['bot', '-recorded_at'], name='bots_heartb_bot_id_b0008f_idx')],
            },
        ),
    ]
