# Generated by Django 5.0.4 on 2026-02-28 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_client_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='client_version',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
